version: '3.4'
services:
  worker:
    build: .
    image: &img worker
    command: [celery, worker, --app=worker.celery_app, --pool=gevent, --concurrency=20, --loglevel=INFO]
    environment: &env
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TRAIN_SPEED_SCHEDULE=10
      - STATIONS_SCHEDULE=180
      - LOG_FILES_PATH=/app/logfiles
      - HOST=10.5.0.103
      - PORT=5002
    depends_on:
      - redis
    restart: 'no'
    volumes:
      - ./app:/app
      - worker:/app/logfiles
    networks:
      vpcbr:
        ipv4_address: 10.5.0.100
  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker.celery_app, --loglevel=INFO]
    environment: *env
    depends_on:
      - redis
      - worker
    restart: 'no'
    volumes:
      - ./app:/app
    networks:
      vpcbr:
        ipv4_address: 10.5.0.101
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.102
  lineman_api:
    build:
      context: lineman_api
      dockerfile: Dockerfile
    command: [gunicorn, --bind=10.5.0.103:5002, --workers=3, wsgi:app]
    ports:
      - "127.0.0.1:5002:5002"
    environment:
      - HOST=10.5.0.103
      - PORT=5002
      - SQLALCHEMY_DATABASE_URI=sqlite:////tmp/test.db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.103
volumes:
  worker:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
