version: '3.4'
services:
  worker:
    build: .
    image: &img worker
    command: [celery, worker, --app=worker, --pool=gevent, --concurrency=20, --loglevel=INFO]
    environment: &env
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TRAIN_SPEED_SCHEDULE=10
      - STATIONS_SCHEDULE=180
    depends_on:
      - beat
      - rabbitmq
    restart: 'no'
    volumes:
      - ./app:/app
      - worker:/logfiles
  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker, --loglevel=INFO]
    environment: *env
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - ./app:/app
  rabbitmq:
    image: rabbitmq:3.7.8
volumes:
  worker:
