version: '3.4'
services:
  worker:
    build: .
    image: &img worker
    command: [celery, worker, --app=worker.celery_app, --pool=gevent, --concurrency=20, --loglevel=INFO]
    environment: &env
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TRAIN_SPEED_SCHEDULE=10
      - STATIONS_SCHEDULE=180
      - LOG_FILES_PATH=/app/logfiles
      - HOST=localhost
      - PORT=5002
    depends_on:
      - beat
      - redis
    restart: 'no'
    volumes:
      - ./app:/app
      - worker:/app/logfiles
  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker.celery_app, --loglevel=INFO]
    environment: *env
    depends_on:
      - redis
    restart: 'no'
    volumes:
      - ./app:/app
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  lineman_api:
    build:
      context: lineman_api
      dockerfile: Dockerfile
    command: [gunicorn, --bin=0.0.0.0:5002, --workers=3, wsgi:lineman_app]
    ports:
      - "127.0.0.1:5002:5002"
    environment:
      - HOST=localhost
      - PORT=5002
volumes:
  worker:
